apiVersion: v1
kind: ReplicationController
metadata:
  name: apache-forward-proxy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: apache-forward-proxy
    spec:
      containers:
      - image: moander/mod_proxy
        name: httpd
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 1080
