apiVersion: v1
kind: Service
metadata:
  name: apache-forward-proxy
spec:
  selector:
    app: apache-forward-proxy
  ports:
  - port: 80
    name: http
    targetPort: http
  - port: 1080
    name: socks
    targetPort: http
